# Generated by Django 5.2.13 on 2026-04-14 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer', models.CharField(max_length=20, verbose_name='Numer grobu')),
                ('rzad', models.CharField(blank=True, max_length=20, verbose_name='Rząd')),
                ('typ', models.CharField(choices=[('ziemny', 'Grób ziemny'), ('murowany', 'Grób murowany'), ('rodzinny', 'Grób rodzinny'), ('urnowy', 'Grób urnowy'), ('zbiorowy', 'Grób zbiorowy'), ('inny', 'Inny')], default='ziemny', max_length=20, verbose_name='Typ grobu')),
                ('szerokosc_geo', models.FloatField(blank=True, null=True, verbose_name='Szerokość geograficzna')),
                ('dlugosc_geo', models.FloatField(blank=True, null=True, verbose_name='Długość geograficzna')),
                ('zdjecie', models.ImageField(blank=True, null=True, upload_to='groby/', verbose_name='Zdjęcie')),
                ('uwagi', models.TextField(blank=True, verbose_name='Uwagi')),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('data_modyfikacji', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grób',
                'verbose_name_plural': 'Groby',
                'ordering': ['sektor__nazwa', 'numer'],
            },
        ),
        migrations.CreateModel(
            name='Sektor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50, unique=True, verbose_name='Nazwa sektora')),
                ('opis', models.TextField(blank=True, verbose_name='Opis')),
            ],
            options={
                'verbose_name': 'Sektor',
                'verbose_name_plural': 'Sektory',
                'ordering': ['nazwa'],
            },
        ),
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100, verbose_name='Imię')),
                ('drugie_imie', models.CharField(blank=True, max_length=100, verbose_name='Drugie imię')),
                ('nazwisko', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('nazwisko_rodowe', models.CharField(blank=True, max_length=100, verbose_name='Nazwisko rodowe')),
                ('data_urodzenia', models.DateField(blank=True, null=True, verbose_name='Data urodzenia')),
                ('data_smierci', models.DateField(blank=True, null=True, verbose_name='Data śmierci')),
                ('miejsce_urodzenia', models.CharField(blank=True, max_length=200, verbose_name='Miejsce urodzenia')),
                ('biogram', models.TextField(blank=True, verbose_name='Biogram / uwagi')),
                ('grob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='osoby', to='groby.grob', verbose_name='Grób')),
            ],
            options={
                'verbose_name': 'Osoba',
                'verbose_name_plural': 'Osoby',
                'ordering': ['nazwisko', 'imie'],
            },
        ),
        migrations.AddField(
            model_name='grob',
            name='sektor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groby', to='groby.sektor', verbose_name='Sektor'),
        ),
        migrations.AlterUniqueTogether(
            name='grob',
            unique_together={('sektor', 'numer')},
        ),
    ]
