# Generated by Django 5.2.13 on 2026-05-06 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groby', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grob',
            options={'ordering': ['sektor__nazwa', 'rzad', 'numer'], 'verbose_name': 'Grób', 'verbose_name_plural': 'Groby'},
        ),
        migrations.AlterUniqueTogether(
            name='grob',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='grob',
            name='link_zdjecia',
            field=models.URLField(blank=True, max_length=500, verbose_name='Link do zdjęcia nagrobka'),
        ),
        migrations.AddField(
            model_name='grob',
            name='numer_aktu',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numer aktu w księdze zmarłych'),
        ),
        migrations.AddField(
            model_name='grob',
            name='oplata',
            field=models.CharField(blank=True, choices=[('tak', 'Tak'), ('nie', 'Nie'), ('brak_danych', 'Brak danych')], max_length=20, verbose_name='Opłata za nagrobek'),
        ),
        migrations.AddField(
            model_name='grob',
            name='rodzaj_opis',
            field=models.CharField(blank=True, max_length=255, verbose_name='Rodzaj nagrobka (opis)'),
        ),
        migrations.AlterField(
            model_name='grob',
            name='sektor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groby', to='groby.sektor', verbose_name='Sektor (kwatera)'),
        ),
        migrations.AlterUniqueTogether(
            name='grob',
            unique_together={('sektor', 'rzad', 'numer')},
        ),
    ]
