# Generated by Django 5.2.13 on 2026-05-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groby', '0002_alter_grob_options_alter_grob_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grob',
            name='plan_x',
            field=models.FloatField(blank=True, null=True, verbose_name='Pozycja X na planie (px)'),
        ),
        migrations.AddField(
            model_name='grob',
            name='plan_y',
            field=models.FloatField(blank=True, null=True, verbose_name='Pozycja Y na planie (px)'),
        ),
    ]
