# Generated by Django 5.2.13 on 2026-05-06 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groby', '0003_grob_plan_x_grob_plan_y'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokrewienstwo', models.CharField(blank=True, max_length=200, verbose_name='Pokrewieństwo / opis')),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('obserwowane_groby', models.ManyToManyField(blank=True, related_name='obserwujacy', to='groby.grob', verbose_name='Obserwowane groby')),
                ('obserwowane_osoby', models.ManyToManyField(blank=True, related_name='obserwujacy', to='groby.osoba', verbose_name='Obserwowane osoby')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil użytkownika',
                'verbose_name_plural': 'Profile użytkowników',
            },
        ),
        migrations.CreateModel(
            name='Zdjecie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plik', models.ImageField(upload_to='groby/galeria/', verbose_name='Zdjęcie')),
                ('podpis', models.CharField(blank=True, max_length=200, verbose_name='Podpis')),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('kolejnosc', models.PositiveSmallIntegerField(default=0, verbose_name='Kolejność')),
                ('grob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zdjecia', to='groby.grob', verbose_name='Grób')),
            ],
            options={
                'verbose_name': 'Zdjęcie',
                'verbose_name_plural': 'Zdjęcia',
                'ordering': ['kolejnosc', 'data_dodania'],
            },
        ),
        migrations.CreateModel(
            name='Zgloszenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(default='poprawka', max_length=50, verbose_name='Typ zgłoszenia')),
                ('tresc', models.TextField(verbose_name='Treść zgłoszenia')),
                ('autor_imie', models.CharField(blank=True, max_length=100, verbose_name='Imię i nazwisko zgłaszającego')),
                ('autor_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail (opcjonalnie)')),
                ('status', models.CharField(choices=[('nowe', 'Nowe'), ('w_trakcie', 'W trakcie'), ('zaakceptowane', 'Zaakceptowane'), ('odrzucone', 'Odrzucone')], default='nowe', max_length=20)),
                ('odpowiedz', models.TextField(blank=True, verbose_name='Odpowiedź administratora')),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('data_modyfikacji', models.DateTimeField(auto_now=True)),
                ('autor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zgloszenia', to=settings.AUTH_USER_MODEL, verbose_name='Konto')),
                ('grob', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zgloszenia', to='groby.grob', verbose_name='Grób')),
                ('osoba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zgloszenia', to='groby.osoba', verbose_name='Osoba')),
            ],
            options={
                'verbose_name': 'Zgłoszenie',
                'verbose_name_plural': 'Zgłoszenia',
                'ordering': ['-data_dodania'],
            },
        ),
        migrations.CreateModel(
            name='HistoriaZmian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('obiekt_id', models.PositiveIntegerField()),
                ('obiekt_repr', models.CharField(max_length=255)),
                ('akcja', models.CharField(choices=[('dodano', 'Dodano'), ('zmieniono', 'Zmieniono'), ('usunieto', 'Usunięto')], max_length=20)),
                ('pola', models.JSONField(blank=True, default=dict, verbose_name='Zmienione pola')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historia zmiany',
                'verbose_name_plural': 'Historia zmian',
                'ordering': ['-data'],
                'indexes': [models.Index(fields=['model', 'obiekt_id'], name='groby_histo_model_c6168c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Relacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('rodzic', 'Rodzic — Dziecko'), ('malzenstwo', 'Małżeństwo'), ('rodzenstwo', 'Rodzeństwo'), ('inny', 'Inna relacja')], max_length=20, verbose_name='Typ relacji')),
                ('uwagi', models.CharField(blank=True, max_length=255)),
                ('osoba_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacje_a', to='groby.osoba', verbose_name='Osoba A (np. rodzic)')),
                ('osoba_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacje_b', to='groby.osoba', verbose_name='Osoba B (np. dziecko)')),
            ],
            options={
                'verbose_name': 'Relacja rodzinna',
                'verbose_name_plural': 'Relacje rodzinne',
                'unique_together': {('osoba_a', 'osoba_b', 'typ')},
            },
        ),
    ]
