# Generated by Django 5.2.13 on 2026-05-06 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groby', '0005_osoba_fts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Swieca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intencja', models.CharField(blank=True, max_length=200, verbose_name='Intencja / dedykacja')),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('data_zapalenia', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('autor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swiece', to=settings.AUTH_USER_MODEL)),
                ('osoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swiece', to='groby.osoba', verbose_name='Osoba')),
            ],
            options={
                'verbose_name': 'Świeczka',
                'verbose_name_plural': 'Świeczki',
                'ordering': ['-data_zapalenia'],
            },
        ),
        migrations.CreateModel(
            name='Wspomnienie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_imie', models.CharField(blank=True, max_length=100, verbose_name='Imię i nazwisko zgłaszającego')),
                ('tresc', models.TextField(verbose_name='Treść wspomnienia')),
                ('status', models.CharField(choices=[('oczekuje', 'Oczekuje'), ('zaakceptowane', 'Zaakceptowane'), ('odrzucone', 'Odrzucone')], default='oczekuje', max_length=20)),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('autor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wspomnienia', to=settings.AUTH_USER_MODEL)),
                ('osoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wspomnienia', to='groby.osoba', verbose_name='Osoba')),
            ],
            options={
                'verbose_name': 'Wspomnienie',
                'verbose_name_plural': 'Wspomnienia',
                'ordering': ['-data_dodania'],
            },
        ),
    ]
