# Generated by Django 5.2.13 on 2026-05-08 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groby', '0006_swieca_wspomnienie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wpis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('postac', 'Znana postać'), ('wydarzenie', 'Wydarzenie'), ('historia', 'Tekst historyczny')], default='postac', max_length=20)),
                ('tytul', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('podpis', models.CharField(blank=True, max_length=300, verbose_name='Krótki opis (lead)')),
                ('tresc', models.TextField()),
                ('zdjecie', models.ImageField(blank=True, null=True, upload_to='wpisy/')),
                ('data_publikacji', models.DateField(blank=True, null=True, verbose_name='Data publikacji')),
                ('opublikowany', models.BooleanField(default=False)),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('data_modyfikacji', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('osoba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wpisy', to='groby.osoba', verbose_name='Powiązana osoba (opcjonalnie)')),
            ],
            options={
                'verbose_name': 'Wpis (blog/postać)',
                'verbose_name_plural': 'Wpisy (blog/postacie)',
                'ordering': ['-data_publikacji', '-data_dodania'],
            },
        ),
        migrations.CreateModel(
            name='ZapisaneSzukanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, verbose_name='Nazwa wyszukiwania')),
                ('querystring', models.CharField(max_length=500, verbose_name='Parametry filtru')),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('ostatnie_uzycie', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zapisane_szukania', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zapisane wyszukiwanie',
                'verbose_name_plural': 'Zapisane wyszukiwania',
                'ordering': ['-ostatnie_uzycie', '-data_utworzenia'],
            },
        ),
    ]
