# Generated by Django 5.2.13 on 2026-05-08 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groby', '0007_wpis_zapisaneszukanie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Panorama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('plik', models.ImageField(upload_to='panoramy/')),
                ('opis', models.TextField(blank=True)),
                ('pitch', models.FloatField(default=0, help_text='Domyślny pitch widoku w stopniach')),
                ('yaw', models.FloatField(default=0, help_text='Domyślny yaw widoku w stopniach')),
                ('hfov', models.FloatField(default=110, help_text='Domyślny horizontal FOV')),
                ('kolejnosc', models.PositiveSmallIntegerField(default=0)),
                ('sektor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panoramy', to='groby.sektor')),
            ],
            options={
                'verbose_name': 'Panorama 360°',
                'verbose_name_plural': 'Panoramy 360°',
                'ordering': ['kolejnosc', 'nazwa'],
            },
        ),
        migrations.CreateModel(
            name='HotspotPanoramy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch', models.FloatField()),
                ('yaw', models.FloatField()),
                ('etykieta', models.CharField(blank=True, max_length=120)),
                ('grob', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groby.grob')),
                ('docelowa_panorama', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='przejscia_z', to='groby.panorama')),
                ('panorama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspoty', to='groby.panorama')),
            ],
            options={
                'verbose_name': 'Hotspot panoramy',
                'verbose_name_plural': 'Hotspoty panoram',
            },
        ),
        migrations.CreateModel(
            name='SubskrypcjaPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500, unique=True)),
                ('p256dh', models.CharField(max_length=200)),
                ('auth', models.CharField(max_length=80)),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subskrypcje_push', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subskrypcja Push',
                'verbose_name_plural': 'Subskrypcje Push',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('opis', models.CharField(blank=True, max_length=255)),
                ('osoby', models.ManyToManyField(blank=True, related_name='tagi', to='groby.osoba')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tagi',
                'ordering': ['nazwa'],
            },
        ),
        migrations.CreateModel(
            name='TokenLogowania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('data_wygasniecia', models.DateTimeField()),
                ('wykorzystany', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token logowania (magic link)',
                'verbose_name_plural': 'Tokeny logowania',
            },
        ),
    ]
