# Generated by Django 5.2.13 on 2026-05-08 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groby', '0009_komentarz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('aktywny', models.BooleanField(default=True)),
                ('token_anulowania', models.CharField(max_length=64, unique=True)),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('ostatnia_wysylka', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Subskrybent newslettera',
                'verbose_name_plural': 'Subskrybenci newslettera',
            },
        ),
        migrations.CreateModel(
            name='Odznaka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(choices=[('strazn', 'Strażnik pamięci (10 świec)'), ('kron', 'Kronikarz (5 wspomnień)'), ('genea', 'Genealog (3 relacje)'), ('prze', 'Przewodnik (1 trasa)'), ('hist', 'Historyk (1 wpis)')], max_length=20, unique=True)),
                ('nazwa', models.CharField(max_length=100)),
                ('opis', models.TextField(blank=True)),
                ('ikona', models.CharField(default='🏆', help_text='Emoji/glyph', max_length=10)),
            ],
            options={
                'verbose_name': 'Odznaka',
                'verbose_name_plural': 'Odznaki',
            },
        ),
        migrations.CreateModel(
            name='Trasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('opis', models.TextField(blank=True)),
                ('opublikowana', models.BooleanField(default=False)),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trasa zwiedzania',
                'verbose_name_plural': 'Trasy zwiedzania',
                'ordering': ['nazwa'],
            },
        ),
        migrations.CreateModel(
            name='TrasaPunkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolejnosc', models.PositiveSmallIntegerField(default=0)),
                ('podpis', models.TextField(blank=True, verbose_name='Komentarz przewodnika')),
                ('grob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groby.grob')),
                ('trasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punkty', to='groby.trasa')),
            ],
            options={
                'verbose_name': 'Punkt trasy',
                'verbose_name_plural': 'Punkty tras',
                'ordering': ['kolejnosc'],
                'unique_together': {('trasa', 'grob')},
            },
        ),
        migrations.CreateModel(
            name='UzytkownikOdznaka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zdobycia', models.DateTimeField(auto_now_add=True)),
                ('odznaka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groby.odznaka')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odznaki', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_zdobycia'],
                'unique_together': {('user', 'odznaka')},
            },
        ),
    ]
