# Generated by Django 5.2.13 on 2026-05-08 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groby', '0010_newsletter_odznaka_trasa_trasapunkt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200, unique=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('znaleziono', models.BooleanField(default=False)),
                ('data_zapytania', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cache geokodowania',
                'verbose_name_plural': 'Cache geokodowania',
            },
        ),
        migrations.AddField(
            model_name='trasa',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='trasy/audio/', verbose_name='Przewodnik audio (mp3)'),
        ),
        migrations.CreateModel(
            name='IntencjaMszalna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zamawiajacy_imie', models.CharField(max_length=200)),
                ('zamawiajacy_email', models.EmailField(max_length=254)),
                ('zamawiajacy_tel', models.CharField(blank=True, max_length=30)),
                ('intencja', models.TextField()),
                ('proponowana_data', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('nowa', 'Nowa'), ('przyjeta', 'Przyjęta'), ('odprawiona', 'Odprawiona'), ('odrzucona', 'Odrzucona')], default='nowa', max_length=20)),
                ('notatka_kapelana', models.TextField(blank=True)),
                ('data_zlozenia', models.DateTimeField(auto_now_add=True)),
                ('osoba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intencje', to='groby.osoba')),
            ],
            options={
                'verbose_name': 'Intencja mszalna',
                'verbose_name_plural': 'Intencje mszalne',
                'ordering': ['-data_zlozenia'],
            },
        ),
        migrations.CreateModel(
            name='Kwiat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_imie', models.CharField(blank=True, max_length=100)),
                ('wiadomosc', models.CharField(blank=True, max_length=300)),
                ('rodzaj', models.CharField(choices=[('roza', 'Róża'), ('lilia', 'Lilia'), ('chryzantema', 'Chryzantema'), ('tulipan', 'Tulipan')], default='roza', max_length=20)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('data_zlozenia', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('autor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('osoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kwiaty', to='groby.osoba')),
            ],
            options={
                'verbose_name': 'Kwiat',
                'verbose_name_plural': 'Kwiaty',
                'ordering': ['-data_zlozenia'],
            },
        ),
        migrations.CreateModel(
            name='Nagranie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('audio', 'Audio'), ('video', 'Wideo')], default='audio', max_length=10)),
                ('plik', models.FileField(upload_to='nagrania/')),
                ('tytul', models.CharField(max_length=200)),
                ('opis', models.TextField(blank=True)),
                ('zaakceptowane', models.BooleanField(default=False)),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('autor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('grob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nagrania', to='groby.grob')),
                ('osoba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nagrania', to='groby.osoba')),
            ],
            options={
                'verbose_name': 'Nagranie',
                'verbose_name_plural': 'Nagrania',
                'ordering': ['-data_dodania'],
            },
        ),
        migrations.CreateModel(
            name='Zaproszenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('data_wykorzystania', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('osoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zaproszenia', to='groby.osoba')),
                ('wykorzystane_przez', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='przyjete_zaproszenia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zaproszenie do edycji',
                'verbose_name_plural': 'Zaproszenia do edycji',
            },
        ),
        migrations.CreateModel(
            name='GlosNagrobek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_hash', models.CharField(max_length=64)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('grob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glosy', to='groby.grob')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Głos w plebiscycie',
                'verbose_name_plural': 'Głosy w plebiscycie',
                'unique_together': {('grob', 'ip_hash')},
            },
        ),
    ]
