# Generated by Django 5.2.13 on 2026-05-08 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groby', '0011_geocache_trasa_audio_intencjamszalna_kwiat_nagranie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZdjecieWpisu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plik', models.ImageField(upload_to='wpisy/galeria/')),
                ('podpis', models.CharField(blank=True, max_length=200)),
                ('kolejnosc', models.PositiveSmallIntegerField(default=0)),
                ('wpis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zdjecia_dodatkowe', to='groby.wpis')),
            ],
            options={
                'verbose_name': 'Zdjęcie wpisu',
                'verbose_name_plural': 'Zdjęcia wpisów',
                'ordering': ['kolejnosc'],
            },
        ),
    ]
