# Generated by Django 5.2.13 on 2026-05-09 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groby', '0013_indeksy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_imie', models.CharField(blank=True, max_length=100)),
                ('tresc', models.TextField()),
                ('publiczny', models.BooleanField(default=False, verbose_name='Publiczny (widoczny na ścianie)')),
                ('zaakceptowany', models.BooleanField(default=False)),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'List do zmarłego',
                'verbose_name_plural': 'Listy do zmarłych',
                'ordering': ['-data_dodania'],
            },
        ),
        migrations.CreateModel(
            name='PostForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField()),
                ('zaakceptowany', models.BooleanField(default=False)),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Post w forum',
                'verbose_name_plural': 'Posty w forum',
                'ordering': ['data_dodania'],
            },
        ),
        migrations.CreateModel(
            name='PytanieQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pytanie', models.CharField(max_length=500)),
                ('odpowiedzi', models.JSONField(help_text='Lista 4 odpowiedzi (pierwsza jest poprawna).')),
                ('wyjasnienie', models.TextField(blank=True)),
                ('aktywne', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pytanie quiz',
                'verbose_name_plural': 'Pytania quizu',
            },
        ),
        migrations.CreateModel(
            name='WatekForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=200)),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('data_ostatniego_postu', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Wątek forum',
                'verbose_name_plural': 'Wątki forum',
                'ordering': ['-data_ostatniego_postu'],
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('event', models.CharField(choices=[('zgloszenie.nowe', 'Nowe zgłoszenie'), ('wspomnienie.zaakceptowane', 'Zaakceptowane wspomnienie'), ('osoba.dodano', 'Dodana osoba'), ('grob.zmieniono', 'Zmieniono grób')], max_length=50)),
                ('sekret', models.CharField(blank=True, help_text='Sekret do HMAC walidacji', max_length=64)),
                ('aktywny', models.BooleanField(default=True)),
                ('licznik_wywolan', models.PositiveIntegerField(default=0)),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Webhook',
                'verbose_name_plural': 'Webhooki',
            },
        ),
        migrations.RemoveIndex(
            model_name='grob',
            name='grob_pozycja_idx',
        ),
        migrations.RemoveIndex(
            model_name='osoba',
            name='osoba_nazw_imie_idx',
        ),
        migrations.RemoveIndex(
            model_name='osoba',
            name='osoba_data_smierci_idx',
        ),
        migrations.AddField(
            model_name='profil',
            name='onboarding_zakonczony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='list',
            name='autor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='list',
            name='osoba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listy', to='groby.osoba'),
        ),
        migrations.AddField(
            model_name='postforum',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pytaniequiz',
            name='osoba',
            field=models.ForeignKey(blank=True, help_text='Osoba związana z pytaniem.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='groby.osoba'),
        ),
        migrations.AddField(
            model_name='watekforum',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='watekforum',
            name='grob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watki', to='groby.grob'),
        ),
        migrations.AddField(
            model_name='postforum',
            name='watek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posty', to='groby.watekforum'),
        ),
    ]
