# Generated by Django 5.2.13 on 2026-05-09 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groby', '0014_list_postforum_pytaniequiz_watekforum_webhook_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KonkursFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('opis', models.TextField(blank=True)),
                ('data_start', models.DateField()),
                ('data_koniec', models.DateField()),
                ('aktywny', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Konkurs fotograficzny',
                'verbose_name_plural': 'Konkursy fotograficzne',
            },
        ),
        migrations.CreateModel(
            name='WyszukiwanieLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraza', models.CharField(max_length=200)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('liczba_wynikow', models.IntegerField(default=0)),
                ('data', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log wyszukiwania',
                'verbose_name_plural': 'Logi wyszukiwań',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='ZdjecieDronowe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plik', models.ImageField(upload_to='drony/')),
                ('tytul', models.CharField(max_length=200)),
                ('opis', models.TextField(blank=True)),
                ('data_wykonania', models.DateField(blank=True, null=True)),
                ('kolejnosc', models.PositiveSmallIntegerField(default=0)),
                ('sektor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groby.sektor')),
            ],
            options={
                'verbose_name': 'Zdjęcie z drona',
                'verbose_name_plural': 'Zdjęcia z drona',
                'ordering': ['kolejnosc'],
            },
        ),
        migrations.CreateModel(
            name='ZgloszenieKonkursowe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_imie', models.CharField(blank=True, max_length=100)),
                ('plik', models.ImageField(upload_to='konkurs/')),
                ('tytul', models.CharField(blank=True, max_length=200)),
                ('zaakceptowane', models.BooleanField(default=False)),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('grob', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groby.grob')),
                ('konkurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zgloszenia_foto', to='groby.konkursfoto')),
            ],
        ),
        migrations.CreateModel(
            name='GlosKonkursowy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_hash', models.CharField(max_length=64)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zgloszenie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glosy', to='groby.zgloszeniekonkursowe')),
            ],
            options={
                'unique_together': {('zgloszenie', 'ip_hash')},
            },
        ),
    ]
