# Generated by Django 5.2.13 on 2026-05-09 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groby', '0015_konkursfoto_wyszukiwanielog_zdjeciedronowe_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TagWpisu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('opis', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Tag wpisu',
                'verbose_name_plural': 'Tagi wpisów',
                'ordering': ['nazwa'],
            },
        ),
        migrations.AddField(
            model_name='hotspotpanoramy',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='panoramy/audio/', verbose_name='Audio przewodnik (MP3)'),
        ),
        migrations.AddField(
            model_name='webhook',
            name='typ',
            field=models.CharField(choices=[('generic', 'Generyczny POST JSON'), ('discord', 'Discord'), ('slack', 'Slack')], default='generic', max_length=20),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='sekret',
            field=models.CharField(blank=True, help_text='Sekret do HMAC walidacji (tylko generic)', max_length=64),
        ),
        migrations.CreateModel(
            name='FeaturedTygodnia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategoria', models.CharField(choices=[('osoba', 'Osoba'), ('grob', 'Grób'), ('wpis', 'Wpis (postać/wydarzenie)')], max_length=20)),
                ('tytul', models.CharField(max_length=200)),
                ('opis', models.CharField(blank=True, max_length=400)),
                ('od', models.DateField()),
                ('do', models.DateField()),
                ('aktywne', models.BooleanField(default=True)),
                ('grob', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groby.grob')),
                ('osoba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groby.osoba')),
                ('wpis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groby.wpis')),
            ],
            options={
                'verbose_name': 'Wyróżnienie tygodnia',
                'verbose_name_plural': 'Wyróżnienia tygodnia',
                'ordering': ['-od'],
            },
        ),
        migrations.AddField(
            model_name='wpis',
            name='tagi_tresci',
            field=models.ManyToManyField(blank=True, related_name='wpisy', to='groby.tagwpisu', verbose_name='Tagi tematyczne'),
        ),
        migrations.CreateModel(
            name='OdwiedzinyOsoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True)),
                ('licznik', models.PositiveIntegerField(default=0)),
                ('osoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odwiedziny', to='groby.osoba')),
            ],
            options={
                'verbose_name': 'Licznik odwiedzin osoby',
                'verbose_name_plural': 'Liczniki odwiedzin osób',
                'ordering': ['-data'],
                'unique_together': {('osoba', 'data')},
            },
        ),
        migrations.CreateModel(
            name='PlanZwiedzania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesja_id', models.CharField(blank=True, help_text='Identyfikator sesji dla anonimowych', max_length=64)),
                ('odwiedzony', models.BooleanField(default=False)),
                ('notatka', models.CharField(blank=True, max_length=300)),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('grob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='w_planach', to='groby.grob')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_zwiedzania', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan zwiedzania',
                'verbose_name_plural': 'Plany zwiedzania',
                'ordering': ['odwiedzony', '-data_dodania'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'grob'), name='plan_user_grob_uniq'), models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('sesja_id', 'grob'), name='plan_sesja_grob_uniq')],
            },
        ),
    ]
