# Generated by Django 5.2.13 on 2026-05-09 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groby', '0016_tagwpisu_hotspotpanoramy_audio_webhook_typ_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HasloSlownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haslo', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('kategoria', models.CharField(choices=[('postac', 'Postać'), ('miejsce', 'Miejsce'), ('wydarzenie', 'Wydarzenie'), ('termin', 'Termin'), ('inne', 'Inne')], default='termin', max_length=20)),
                ('skrot', models.CharField(blank=True, help_text='Krótka definicja (na liście)', max_length=300)),
                ('tresc', models.TextField()),
                ('zrodla', models.TextField(blank=True, help_text='Źródła, jedno na linię')),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('data_modyfikacji', models.DateTimeField(auto_now=True)),
                ('powiazana_osoba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hasla_slownika', to='groby.osoba')),
            ],
            options={
                'verbose_name': 'Hasło słownika',
                'verbose_name_plural': 'Słownik historii',
                'ordering': ['haslo'],
            },
        ),
        migrations.CreateModel(
            name='Powiadomienie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('komentarz', 'Nowy komentarz'), ('forum', 'Odpowiedź na forum'), ('zgloszenie', 'Status zgłoszenia'), ('opieka', 'Opieka nad grobem'), ('inne', 'Inne')], default='inne', max_length=20)),
                ('tresc', models.CharField(max_length=300)),
                ('url', models.CharField(blank=True, max_length=300)),
                ('przeczytane', models.BooleanField(db_index=True, default=False)),
                ('data', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='powiadomienia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Powiadomienie',
                'verbose_name_plural': 'Powiadomienia',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='OpiekunGrobu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relacja', models.CharField(blank=True, help_text='Np. wnuk, prawnuczka, sąsiad', max_length=100)),
                ('status', models.CharField(choices=[('oczekuje', 'Oczekuje na akceptację'), ('aktywny', 'Aktywny opiekun'), ('odrzucony', 'Odrzucony'), ('zakonczony', 'Opieka zakończona')], default='oczekuje', max_length=20)),
                ('motywacja', models.TextField(blank=True, help_text='Dlaczego chcesz opiekować się tym grobem')),
                ('data_zgloszenia', models.DateTimeField(auto_now_add=True)),
                ('data_zmiany', models.DateTimeField(auto_now=True)),
                ('grob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opiekunowie', to='groby.grob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opieka_groby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opiekun grobu',
                'verbose_name_plural': 'Opiekunowie grobów',
                'ordering': ['-data_zmiany'],
                'constraints': [models.UniqueConstraint(fields=('grob', 'user'), name='opiekun_grob_user_uniq')],
            },
        ),
        migrations.CreateModel(
            name='PrywatnaNotatka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField()),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('data_modyfikacji', models.DateTimeField(auto_now=True)),
                ('osoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prywatne_notatki', to='groby.osoba')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prywatne_notatki', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prywatna notatka',
                'verbose_name_plural': 'Prywatne notatki',
                'ordering': ['-data_modyfikacji'],
                'indexes': [models.Index(fields=['user', 'osoba'], name='groby_prywa_user_id_fdf451_idx')],
            },
        ),
    ]
