# Generated by Django 5.2.13 on 2026-05-09 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groby', '0017_batch91_powiadomienia_opiekun_notatka_slownik'),
    ]

    operations = [
        migrations.CreateModel(
            name='WydarzenieParafialne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=200)),
                ('typ', models.CharField(choices=[('msza', 'Msza święta'), ('procesja', 'Procesja'), ('modlitwa', 'Modlitwa za zmarłych'), ('porzadkowanie', 'Porządkowanie cmentarza'), ('inne', 'Inne')], default='msza', max_length=20)),
                ('data_start', models.DateTimeField(db_index=True)),
                ('data_koniec', models.DateTimeField(blank=True, null=True)),
                ('miejsce', models.CharField(blank=True, help_text='Np. Kościół św. Władysława, brama cmentarza', max_length=200)),
                ('opis', models.TextField(blank=True)),
                ('intencja', models.CharField(blank=True, help_text='Intencja mszy / modlitwy (opcjonalnie)', max_length=300)),
                ('opublikowane', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Wydarzenie parafialne',
                'verbose_name_plural': 'Wydarzenia parafialne',
                'ordering': ['data_start'],
            },
        ),
        migrations.CreateModel(
            name='EtykietaOsoby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('opis', models.CharField(blank=True, max_length=300)),
                ('ikona', models.CharField(blank=True, help_text='Krótki znak/emoji do listy', max_length=8)),
                ('kolor', models.CharField(blank=True, help_text='Klasa Tailwind kolor (np. bg-amber-100 text-amber-800)', max_length=20)),
                ('osoby', models.ManyToManyField(blank=True, related_name='etykiety', to='groby.osoba')),
            ],
            options={
                'verbose_name': 'Etykieta osoby',
                'verbose_name_plural': 'Etykiety osób',
                'ordering': ['nazwa'],
            },
        ),
    ]
