# Generated by Django 5.2.13 on 2026-05-09 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groby', '0018_batch92_etykiety_wydarzenie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sonda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pytanie', models.CharField(max_length=300)),
                ('opis', models.TextField(blank=True)),
                ('aktywna', models.BooleanField(db_index=True, default=True)),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('data_zakonczenia', models.DateField(blank=True, help_text='Po tej dacie sonda zamyka się automatycznie', null=True)),
            ],
            options={
                'verbose_name': 'Sonda',
                'verbose_name_plural': 'Sondy',
                'ordering': ['-data_utworzenia'],
            },
        ),
        migrations.AddField(
            model_name='osoba',
            name='epitafium',
            field=models.CharField(blank=True, max_length=400, verbose_name='Epitafium / motto na nagrobku'),
        ),
        migrations.CreateModel(
            name='Kondolencja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_imie', models.CharField(blank=True, max_length=100)),
                ('tresc', models.TextField()),
                ('zaakceptowana', models.BooleanField(db_index=True, default=False)),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('autor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('osoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kondolencje', to='groby.osoba')),
            ],
            options={
                'verbose_name': 'Kondolencja',
                'verbose_name_plural': 'Kondolencje',
                'ordering': ['-data_dodania'],
            },
        ),
        migrations.CreateModel(
            name='NotkaCmentarna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.CharField(max_length=500)),
                ('przypiety', models.BooleanField(default=False, help_text='Wyświetlaj na górze')),
                ('opublikowana', models.BooleanField(db_index=True, default=True)),
                ('data_dodania', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notka cmentarna',
                'verbose_name_plural': 'Notki cmentarne',
                'ordering': ['-przypiety', '-data_dodania'],
            },
        ),
        migrations.CreateModel(
            name='OdpowiedzSondy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.CharField(max_length=200)),
                ('kolejnosc', models.PositiveSmallIntegerField(default=0)),
                ('sonda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odpowiedzi', to='groby.sonda')),
            ],
            options={
                'verbose_name': 'Odpowiedź sondy',
                'verbose_name_plural': 'Odpowiedzi sondy',
                'ordering': ['kolejnosc', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ZbiorkaRenowacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=200)),
                ('opis', models.TextField()),
                ('cel_pln', models.PositiveIntegerField(help_text='Kwota docelowa w PLN')),
                ('zebrano_pln', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('oczekuje', 'Oczekuje na akceptację'), ('aktywna', 'Aktywna'), ('zakonczona', 'Zakończona'), ('odrzucona', 'Odrzucona')], db_index=True, default='oczekuje', max_length=20)),
                ('konto_bankowe', models.CharField(blank=True, help_text='Numer konta na wpłaty', max_length=80)),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('data_zmiany', models.DateTimeField(auto_now=True)),
                ('grob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zbiorki', to='groby.grob')),
                ('inicjator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zbiórka renowacyjna',
                'verbose_name_plural': 'Zbiórki renowacyjne',
                'ordering': ['-data_utworzenia'],
            },
        ),
        migrations.CreateModel(
            name='GlosSondy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_hash', models.CharField(max_length=64)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('odpowiedz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glosy', to='groby.odpowiedzsondy')),
            ],
            options={
                'verbose_name': 'Głos w sondzie',
                'verbose_name_plural': 'Głosy w sondach',
                'constraints': [models.UniqueConstraint(fields=('odpowiedz', 'ip_hash'), name='glos_sondy_odp_ip_uniq')],
            },
        ),
    ]
