# Generated by Django 5.2.13 on 2026-05-10 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groby', '0020_fts_triggers_rebuild'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WpisLapidarium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=200)),
                ('kategoria', models.CharField(choices=[('zabytek', 'Nagrobek zabytkowy'), ('artyzm', 'Walory artystyczne'), ('historia', 'Znaczenie historyczne'), ('symbolika', 'Symbolika'), ('inne', 'Inne')], default='zabytek', max_length=20)),
                ('opis_kuratorski', models.TextField(help_text='Co warto zauważyć w tym nagrobku')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='lapidarium/')),
                ('rok_powstania', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('autor_nagrobka', models.CharField(blank=True, help_text='Kamieniarz / artysta, jeśli znany', max_length=200)),
                ('kolejnosc', models.PositiveSmallIntegerField(default=0, help_text='Kolejność na liście (mniejsza = wyżej)')),
                ('opublikowany', models.BooleanField(db_index=True, default=True)),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('grob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wpisy_lapidarium', to='groby.grob')),
            ],
            options={
                'verbose_name': 'Wpis lapidarium',
                'verbose_name_plural': 'Lapidarium',
                'ordering': ['kolejnosc', '-data_dodania'],
            },
        ),
        migrations.CreateModel(
            name='ModlitwaDziennie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_hash', models.CharField(max_length=64)),
                ('data', models.DateField(auto_now_add=True, db_index=True)),
                ('osoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modlitwy', to='groby.osoba')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modlitwa za zmarłego',
                'verbose_name_plural': 'Modlitwy za zmarłych',
                'indexes': [models.Index(fields=['osoba', 'data'], name='groby_modli_osoba_i_f864d9_idx')],
                'constraints': [models.UniqueConstraint(fields=('osoba', 'ip_hash', 'data'), name='modlitwa_uniq')],
            },
        ),
    ]
