# Generated by Django 5.2.13 on 2026-05-10 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groby', '0021_batch94_lapidarium_modlitwa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiwalneZdjecie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='archiwalne/')),
                ('opis', models.CharField(max_length=300)),
                ('rok', models.PositiveSmallIntegerField(blank=True, help_text='Rok wykonania zdjęcia', null=True)),
                ('zrodlo', models.CharField(blank=True, help_text='Skąd zdjęcie (album rodzinny, archiwum…)', max_length=200)),
                ('autor_imie', models.CharField(blank=True, max_length=100)),
                ('zaakceptowane', models.BooleanField(db_index=True, default=False)),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('autor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('osoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archiwalne', to='groby.osoba')),
            ],
            options={
                'verbose_name': 'Archiwalne zdjęcie',
                'verbose_name_plural': 'Archiwalne zdjęcia',
                'ordering': ['rok', 'data_dodania'],
            },
        ),
        migrations.CreateModel(
            name='OgloszenieGenealogiczne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_imie', models.CharField(blank=True, max_length=100)),
                ('autor_kontakt', models.CharField(blank=True, help_text='E-mail / telefon (publiczne)', max_length=200)),
                ('typ', models.CharField(choices=[('szukam_potomkow', 'Szukam potomków'), ('szukam_przodkow', 'Szukam przodków'), ('mam_dokumenty', 'Mam dokumenty / fotografie'), ('inne', 'Inne')], default='szukam_potomkow', max_length=20)),
                ('nazwisko', models.CharField(blank=True, db_index=True, help_text='Nazwisko, którego szukasz', max_length=100)),
                ('tresc', models.TextField()),
                ('zaakceptowane', models.BooleanField(db_index=True, default=False)),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('powiazana_osoba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groby.osoba')),
            ],
            options={
                'verbose_name': 'Ogłoszenie genealogiczne',
                'verbose_name_plural': 'Tablica poszukiwań genealogicznych',
                'ordering': ['-data_dodania'],
            },
        ),
        migrations.CreateModel(
            name='ZadanieTranskrypcji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='transkrypcje/')),
                ('opis', models.CharField(help_text='Co widać, lokalizacja na nagrobku', max_length=300)),
                ('status', models.CharField(choices=[('otwarte', 'Otwarte'), ('zaakceptowane', 'Transkrypcja zaakceptowana'), ('zamkniete', 'Zamknięte')], db_index=True, default='otwarte', max_length=20)),
                ('zaakceptowana_tresc', models.TextField(blank=True, help_text='Finalna transkrypcja po akceptacji staffu')),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('grob', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zadania_transkrypcji', to='groby.grob')),
            ],
            options={
                'verbose_name': 'Zadanie transkrypcji',
                'verbose_name_plural': 'Zadania transkrypcji',
                'ordering': ['-data_dodania'],
            },
        ),
        migrations.CreateModel(
            name='ProponowanaTranskrypcja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_imie', models.CharField(blank=True, max_length=100)),
                ('tresc', models.TextField()),
                ('glosy', models.PositiveIntegerField(db_index=True, default=0)),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('zadanie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propozycje', to='groby.zadanietranskrypcji')),
            ],
            options={
                'verbose_name': 'Propozycja transkrypcji',
                'verbose_name_plural': 'Propozycje transkrypcji',
                'ordering': ['-glosy', 'data_dodania'],
            },
        ),
        migrations.CreateModel(
            name='GlosTranskrypcja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_hash', models.CharField(max_length=64)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('propozycja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glosujacy', to='groby.proponowanatranskrypcja')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('propozycja', 'ip_hash'), name='glos_transkrypcja_uniq')],
            },
        ),
    ]
