# Generated by Django 5.2.13 on 2026-09-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groby', '0022_batch95_transkrypcja_archiwalne_genealogia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alejka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(blank=True, max_length=100, verbose_name='Nazwa alejki')),
                ('punkty', models.JSONField(default=list, help_text='Lista [x, y] w pikselach skanu planu.', verbose_name='Punkty łamanej')),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alejka',
                'verbose_name_plural': 'Alejki',
                'ordering': ['nazwa', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Brama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(default='Brama główna', max_length=100, verbose_name='Nazwa')),
                ('plan_x', models.FloatField(verbose_name='Pozycja X na planie (px)')),
                ('plan_y', models.FloatField(verbose_name='Pozycja Y na planie (px)')),
            ],
            options={
                'verbose_name': 'Brama',
                'verbose_name_plural': 'Bramy',
                'ordering': ['nazwa'],
            },
        ),
        migrations.AddField(
            model_name='sektor',
            name='liczba_miejsc',
            field=models.PositiveIntegerField(blank=True, help_text='Gdy puste, zajętość liczona jest względem liczby grobów w księdze.', null=True, verbose_name='Liczba miejsc (pojemność kwatery)'),
        ),
    ]
